/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaee7.jsf.request.interceptor;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
