/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.drools;

import org.kie.api.KieBase;
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

public class App {
    private KieServices kieServices;
    private KieContainer kieContainer;
    private KieBase kieBase;
    private KieSession kieSession;

    public static void main(String[] args) {
        App app = new App("mykiebase", "mykiesession");
        System.out.println(app.kieSession);

        {
            Order order = new Order();
            order.setCount(0);
            app.getKieSession().insert(order);
        }
        {
            Order order = new Order();
            order.setCount(-1);
            app.getKieSession().insert(order);
        }
        {
            Order order = new Order();
            order.setCount(1);
            app.getKieSession().insert(order);
        }

        app.getKieSession().fireAllRules();
        app.getKieSession().dispose();
    }

    public App(String kieBaseName, String kieSessionName) {
        // For this simple case it is enough to create a `KieContainer` that reads the files to be built from the classpath:
        // `KieServices` is the interface from where it possible to access all the Kie building and runtime facilities:
        this.kieServices = KieServices.Factory.get();
        // In this way all the Java sources and the Kie resources are compiled and deployed into the KieContainer which makes its contents available for use at runtime.
        this.kieContainer = kieServices.getKieClasspathContainer();

        this.kieBase = this.kieContainer.getKieBase(kieBaseName);
        this.kieSession = this.kieContainer.newKieSession(kieSessionName);
    }

    public KieServices getKieServices() {
        return kieServices;
    }

    public void setKieServices(KieServices kieServices) {
        this.kieServices = kieServices;
    }

    public KieContainer getKieContainer() {
        return kieContainer;
    }

    public void setKieContainer(KieContainer kieContainer) {
        this.kieContainer = kieContainer;
    }

    public KieBase getKieBase() {
        return kieBase;
    }

    public void setKieBase(KieBase kieBase) {
        this.kieBase = kieBase;
    }

    public KieSession getKieSession() {
        return kieSession;
    }

    public void setKieSession(KieSession kieSession) {
        this.kieSession = kieSession;
    }
}
