/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.drools;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void appCanCreateKieContainer() {
        System.out.println("appCanCreateKieContainer");
        App classUnderTest = new App("mykiebase", "mykiesession");
        assertNotNull(classUnderTest.getKieServices(), "app should have a greeting");
        assertNotNull(classUnderTest.getKieContainer(), "app should have a greeting");
        assertNotNull(classUnderTest.getKieBase(), "app should have a greeting");
        assertNotNull(classUnderTest.getKieSession(), "app should have a greeting");
    }

    @Test
    void appCanFireRules() {
        System.out.println("appCanFireRules");
        App classUnderTest = new App("mykiebase", "mykiesession");

        classUnderTest.getKieSession().fireAllRules();
    }
}
