/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package karate.example;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;
import com.intuit.karate.junit5.Karate;

class AppTest {
    // @Karate.Test
    // Karate testUdcHttp() {
    //     return Karate.run().karateEnv("udc").tags("@http").relativeTo(getClass());
    // }

    @Karate.Test
    Karate testUdcE2E() {
        return Karate.run("e2e").karateEnv("udc").tags("@e2e").relativeTo(getClass());
    }

    // @Karate.Test
    // Karate testOcvDebugE2E() {
    //     return Karate.run().karateEnv("ocv-debug").tags("@e2e").relativeTo(getClass());
    // }
}
